### ISSUE TITLE
How to handle images (or other resources) referenced by the scss file?

### ISSUE THREAD

**Issue by schauder** [t-mazgalov/gradle-sass-vaadin-compiler#3]
From the readme, it looks like I can only specify scss or sass files, how should I handle images or similar stuff, that needs to get copied with the processed css? Or should this be handled in a completely separate task in the gradle build?

**Comment by t-mazgalov** [comment]
The task only compiles a sass file to css and doesn't process resources. But with simple Gradle copy task, the resources can be handled easily.

Actually in all my builds the sass and css files are in same directory and  resource handling for me is not needed :)

If you have any ideas for extension of the plugin, I will be glad to hear (read :)) them ;)

**Comment by schauder** [comment]
> But with simple Gradle copy task, the resources can be handled easily.

yep, that's what I did
