### ISSUE TITLE
cssFile should be marked as OutputFile

### ISSUE THREAD

**Issue by Milbor-zz** [t-mazgalov/gradle-sass-vaadin-compiler#4]
https://github.com/t-mazgalov/gradle-sass-vaadin-compiler/blob/9cd16ef8555433da201a14c77fae8ce7f6f9b960/src/main/groovy/name/mazgalov/vaadin/sass/compiler/task/CompileSass.groovy#L16

When attaching compileSass task to processResources by
```processResources.finalizedBy compileSass```
cssFile is regenerated (changed) with each task execution and because it is marked as Input, task gets always executed even though scssFile is the same. This is probably not desirable.
Or what was the reason to mark it as Input?
Thank you.

**Comment by t-mazgalov** [comment]
You have a point, this is a good improvement.
I annotated the input and output files with @InputFile and @OutputFile
Now the scripts configuration must declare the scssFile and cssFile as files :)

**Comment by t-mazgalov** [comment]
Published a new version 0.2.1 to the gradle plugins portal
